### ISSUE TITLE
Thank you for sharing your files.^^

### ISSUE THREAD

**Issue by woainiwoo** [vans163/LKEmuV2#2]
Thank you for sharing your files.^^
But if you look at the miner map, it's supposed to be up to the 9th
Shared files include miner0 to miner4.
I'd like to modify or add a map file.
Do you have a Map Modification Tooler converter?

**Comment by vans163** [comment]
I think they just perhaps reuse the same map layout for some levels.

I do not have such tool but I dumped the formats of all the resources. You can probably make one based off the map format/dump https://github.com/vans163/LKResources/tree/master/mapdump, its pretty simple.

**Comment by woainiwoo** [comment]
답변 감사합니다^^
그방법은 이미 사용하고있습니다~
재사용이 아닌 새로운걸 추가해보고 싶었는데 아쉽네요^^

**Comment by vans163** [comment]
Hey, can you help me with something since you speak korean? Can I reach you on discord / email?

**Comment by woainiwoo** [comment]
I can speak Korean. Because I am Korean..Haha
What's the matter?

**Comment by vans163** [comment]
Was curious about some game related development, wanna chat on discord?

**Comment by woainiwoo** [comment]
I am very interested in programming, but I can't So I am studying alone and studying while comparing with the open source you shared ^^ The Last Kingdom game is my favorite game a long time ago I'd like to ask a lot of things, but when I do that, I don't think I can improve I am trying to fix it myself somehow ^^ To help Thank you so much for your care !!
